apiVersion: v1
kind: Namespace
metadata:
  name: cerebro
  labels:
    name: cerebro


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cerebro-gui
  namespace: cerebro
data:
 CEREBRO: CEREBRO-GUI


---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cerebro
  name: cerebro-gui-test
  namespace: cerebro
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: cerebro
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: cerebro
    spec:
      containers:
      - args:
        - -Dconfig.file=/etc/cerebro/application.conf
        image: lmenezes/cerebro:0.9.4
        imagePullPolicy: Always
        name: cerebro
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/db/cerebro
          name: db
        - mountPath: /etc/cerebro
          name: config
        - mountPath: /opt/cerebro/logs/
          name: logs
        - mountPath: /tmp
          name: tmp
        resources:
          limits:
            cpu: "0.5"
            memory: "500Mi"
          requests:
            cpu: "0.2"
            memory: "100Mi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: db
      - configMap:
          defaultMode: 420
          name: cerebro-gui
        name: config
      - emptyDir: {}
        name: logs
      - emptyDir: {}
        name: tmp

---

apiVersion: v1
kind: Service
metadata:
  name: cerebro-svc
  namespace: cerebro
  labels:
    name: cerebro
spec:
  type: NodePort
  selector:
    app: cerebro
  ports:
   - protocol: TCP
     port: 80
     targetPort: 9000